{% set author = "nschloe" %}
{% set name = "meshzoo" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 55e488e7a96827fa4dc38b7106b51ca046b8117658c11c743a482ef29b64944c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
    - importlib_metadata
    - numpy >=1.20.0
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - importlib_metadata

test:
  imports:
    - meshzoo
  requires:
    - pip
    - pytest
    - pytest-codeblocks
    - pytest-cov
    - matplotlib-base
    - python {{ python_min }}
  source_files:
    - README.md
    - tests
  commands:
    - "python -c \"from pathlib import Path; Path('matplotlibrc').write_text('backend: Template')\""
    - pip check
    - pytest --codeblocks README.md
    - pytest -s tests

about:
  home: https://github.com/{{ author }}/{{ name }}
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Collection of explicitly constructed meshes
  description: |
    When generating meshes for FEM/FVM computations, sometimes your geometry is so simple that you don't need a complex mesh generator (like pygmsh, MeshPy, mshr, pygalmesh, dmsh), but something simple and fast that makes use of the structure of the domain. Enter meshzoo.
  doc_url: https://github.com/nschloe/meshzoo
  dev_url: https://github.com/nschloe/meshzoo

extra:
  recipe-maintainers:
    - lasergyro
